python NewTest.py \
--sys_device_ids='7' \
--test_dir='/world/data-gpu-94/sysu-reid/person-reid-data/Market-1501/Market-1501-v15.09.15/pytorch' \
--model_save_dir='/world/data-gpu-94/sysu-reid/checkpoints/DSR_Market_senet_2' \
--batch_size=32 \
--img_h=224 \
--img_w=224 \
--which_epoch='699' \
--gallery_feature_dir='/world/data-gpu-94/sysu-reid/features_save/DSR_Market_senet_2/gallery' \
--query_feature_dir='/world/data-gpu-94/sysu-reid/features_save/DSR_Market_senet_2/query' \
--useCAM
